yatube/about/urls.py
from django.urls import path

from .views import AuthorPage, TechPage


app_name = 'about'

urlpatterns = [
    path('author/', AuthorPage.as_view(), name='author'),
    path('tech/', TechPage.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_list'),

    path('profile/<str:username>/',
         views.profile,
         name='profile'),

    path('', views.index,
         name='index'),

    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'),

    path('create/',
         views.post_create,
         name='post_create'),

    path('posts/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),

    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),

    path('follow/',
         views.follow_index,
         name='follow_index'),

    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),

    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),

     path('posts/<int:post_id>/like/',
         views.post_like,
         name='post_like'),
         ]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),

    path('signup/',
         views.SignUp.as_view(),
         name='signup'),

    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),
]

yatube/yatube/urls.py
# yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from django.conf import settings

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
<p>© {% now "Y" %} Copyright <span style="color:white">Blogicum</span></p>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:white">Blogicum</span>
    </a>
    {% comment %}
    Меню - список пунктов со стандартными классами Bootsrap.
    Класс nav-pills нужен для выделения активных пунктов 
    {% endcomment %}
    <ul class="nav nav-pills">
      <li class="nav-item">              
        <a class="nav-link 
           {% if request.resolver_match.view_name  == 'about:author' %}
             active
           {% endif %}"
           href="{% url 'about:author' %}">
          Об авторе
        </a>
      </li> 
      <li class="nav-item">              
        <a class="nav-link 
           {% if request.resolver_match.view_name  == 'about:tech' %}
             active
           {% endif %}"
           href="{% url 'about:tech' %}">
          Технологии
        </a>
      </li>
      <!-- Проверка: авторизован ли пользователь? --> 
      {% if request.user.is_authenticated %}
        <li class="nav-item">              
          <a class="nav-link 
             {% if request.resolver_match.view_name  == 'posts:post_create' %}
               active
             {% endif %}"
             href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
          
        </li>
      {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>      