yatube/about/urls.py
from django.urls import path

from .views import AuthorPage, TechPage


app_name = 'about'

urlpatterns = [
    path('author/', AuthorPage.as_view(), name='author'),
    path('tech/', TechPage.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_list'),

    path('profile/<str:username>/',
         views.profile,
         name='profile'),

    path('', views.index,
         name='index'),

    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'),

    path('create/',
         views.post_create,
         name='post_create'),

    path('posts/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),

    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),

    path('follow/',
         views.follow_index,
         name='follow_index'),

    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),

    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),

     path('posts/<int:post_id>/like/',
         views.post_like,
         name='post_like'),
         ]

yatube/yatube/urls.py
# yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from django.conf import settings

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Имя группы', max_length=200)
    slug = models.SlugField('Слаг группы', max_length=20, unique=True)
    description = models.TextField('Описание группы', null=True, blank=True)

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField('Текст поста', help_text='Введите текст поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'image',
        upload_to='posts/',
        blank=True,
        null=True
    )

    is_liked = False
    like_amount = None

    def __str__(self) -> str:
        return self.text[:settings.SHORT_POST_LENGTH]

    class Meta:
        ordering = ('-pub_date',)
        default_related_name = 'posts'
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField('Текст комментария',
                            help_text='Введите текст комментария')
    pub_date = models.DateTimeField('Дата комментария', auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'],
            name='unique_following'
        )]


class Like(models.Model):
    user = models.ForeignKey(
        User,
        related_name='liker',
        on_delete=models.CASCADE,
    )

    post = models.ForeignKey(
        Post,
        related_name='post_like',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=['user', 'post'],
            name='unique_like'
        )]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text', )

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.decorators.cache import cache_page
from django.http import HttpResponseRedirect

from django.conf import settings
from .models import Group, Post, User, Follow, Like
from .forms import PostForm, CommentForm


def pagination(request, some_objs, obj_on_page):
    """Возвращает выбранное количество постов на странице"""
    paginator = Paginator(some_objs, obj_on_page)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


# @cache_page(20, key_prefix='index_page')
def index(request):
    """Отображает посты в хронологическом порядке"""
    posts = Post.objects.all()
    print(request.user)
    for post in posts:
            post.like_amount = Like.objects.filter(post=post).count()
    if request.user.is_authenticated:
        for post in posts:
            is_liked = (Like.objects.filter(user=request.user, post=post).first())
            if is_liked:
                post.is_liked = True
    page_obj = pagination(request, posts, settings.POSTS_ON_PAGE)
    context = {'page_obj': page_obj}
    template = 'posts/index.html'
    return render(request, template, context)


def group_posts(request, slug):
    """Отображает все посты выбранной группы"""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = pagination(request, posts, settings.POSTS_ON_PAGE)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Отображает все посты пользователя"""
    author = get_object_or_404(User, username=username)
    posts = Post.objects.select_related('author').filter(author=author)
    post_amount = posts.count()
    page_obj = pagination(request, posts, settings.POSTS_ON_PAGE)
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author)
    )
    context = {'page_obj': page_obj,
               'author': author,
               'post_amount': post_amount,
               'following': following,
               }
    return render(request, 'posts/profile.html', context)


@login_required
def post_create(request):
    """Позволяет создавать новые посты и выбирать теги"""
    form = PostForm(request.POST or None, files=request.FILES or None)

    if not form.is_valid():
        return render(request, 'posts/post_create_form.html', {'form': form})

    form.instance.author = request.user
    form.save()
    return redirect(
        reverse('posts:profile', kwargs={'username': request.user.username})
    )


def post_detail(request, post_id):
    """Отображает полный текст поста и детали"""
    post = get_object_or_404(Post, id=post_id)
    post_amount = (
        Post.objects.select_related('author').
        filter(author=post.author).count())
    form = CommentForm(request.POST or None)
    post.like_amount = Like.objects.filter(post=post).count()
    if request.user.is_authenticated:
        already_liked = Like.objects.filter(user=request.user, post=post).count()
        if already_liked:
            post.is_liked = True
    context = {'post': post,
               'post_amount': post_amount,
               'comments': post.comments.all(),
               'form': form,}
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_like(request, post_id):
    """Позволяет ставить постам нравлики"""
    print(request)
    post = get_object_or_404(Post, id=post_id)
    existing_like = Like.objects.filter(user=request.user, post=post).first()
    if not existing_like:
        Like(user=request.user, post=post).save()
        # return redirect('posts:post_detail', post_id=post_id)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    existing_like.delete()
    # return redirect('posts:post_detail', post_id=post_id)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def post_edit(request, post_id):
    """Редактирования поста"""
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/post_create_form.html', context)


@login_required
def add_comment(request, post_id):
    """Позволяет добавлять комментарии к постам"""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Выводит посты авторов на которых подписан пользователь"""
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = pagination(request, posts, settings.POSTS_ON_PAGE)
    context = {'page_obj': page_obj, }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Подписаться на автора"""
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(
            user=request.user,
            author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Отписаться от автора"""
    author = get_object_or_404(User, username=username)
    Follow.objects.get(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Это страница с постами авторов, на которых вы подписаны
{% endblock %}
    
{% block content %}
{% include 'posts/includes/switcher.html' %}
  <div class="container py-5">     
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
    {% thumbnail post.image "900x500" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
      <p>{{ post.text }}</p>
      <p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
      </p>    
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group.title }} </a> 
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %} 
  </div>  
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}

{% block content %}

<!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    <h1> {{ group.title }} </h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "900x500" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>  {{ post.text }} </p>
      <p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
      </p>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}   
      <!-- под последним постом нет линии -->
  </div>  
{% endblock %}
     

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Это главная страница проекта Yatube
{% endblock %}
    
{% block content %}
{% include 'posts/includes/switcher.html' %}
  <script>
    let cords = ['scrollX','scrollY'];
    // Перед закрытием записываем в локалсторадж window.scrollX и window.scrollY как scrollX и scrollY
    window.addEventListener('unload', e => cords.forEach(cord => localStorage[cord] = window[cord]));
    // Прокручиваем страницу к scrollX и scrollY из localStorage (либо 0,0 если там еще ничего нет)
    window.scroll(...cords.map(cord => localStorage[cord]));
  </script>
  <div class="container py-5">     
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
    {% thumbnail post.image "900x500" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
      <p>{{ post.text }}</p>
      <p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
      </p>    
      {% if post.group %}
        <p>
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group.title }} </a>
        </p>
      {% endif %}
      {% comment %} {% if request.user.is_authenticated %} {% endcomment %}
      <a class="btn btn-primary" href="{% url 'posts:post_like' post_id=post.id %}">
        {% if not post.is_liked %}
        ♡ {{ post.like_amount }}
        {% else %}
        ♥ {{ post.like_amount }}
        {% endif %}
      </a>
      {% comment %} {% endif %} {% endcomment %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %} 
  </div>  
{% endblock %}

yatube/templates/posts/post_create_form.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block  content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-1">
      <div class="card">
        <div class="card-header">      
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}             
        </div>
        <div class="card-body"> 
          <form class="" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <div class="row justify-content-center">
              <div class="card-body">
                {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endif %}    

                {% for field in form %}
                  <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                    </label>    
                    {{ field }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                {% endfor %}
                <div class="col-md-6 ">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                    Сохранить
                    {% else %}
                    Опубликовать
                    {% endif %}
                  </button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}

  Пост {{ post.text|truncatechars:30 }}
    
{% endblock %}
    
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        <!-- если у поста есть группа -->
        {% if post.group %}   
          <li class="list-group-item">
          Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}  
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span > {{ post_amount }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            Все посты пользователя
          </a>
        </li>         
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x460" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }} ">
      {% endthumbnail %}
      <p>
        {{ post.text }}        
      </p>
      {% if post.author == request.user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post_id=post.id %}">
          редактировать запись
        </a>
      {% endif %}
      <a class="btn btn-primary" href="{% url 'posts:post_like' post_id=post.id %}">
        {% if not post.is_liked %}
          ♡ {{ post.like_amount }}
        {% else %}
          ♥ {{ post.like_amount }}
        {% endif %}
      </a>
      </article>
  </div>
{% include 'posts/includes/comments.html' %} 
{% endblock %}
 

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя  {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ post_amount }} </h3>
    {% comment %} <a href="{% url 'posts:profile_follow' author %}">Подписаться </a>
    <p> </p>
    <a href="{% url 'posts:profile_unfollow' author %}">Отписаться </a> {% endcomment %}
    {% if request.user.is_authenticated %}
    {% if following %}
    <a
    class="btn btn-lg btn-light"
    href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
    Отписаться
  </a>
  {% else %}
  <a
  class="btn btn-lg btn-primary"
  href="{% url 'posts:profile_follow' author.username %}" role="button"
  >
  Подписаться
</a>
{% endif %}
{% endif %}
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "900x500" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>    
        {% if post.group %}
          <p>
            <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
          </p>
          <p>
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group.title }} </a>
          </p>
        {% endif %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
      </div>
      {% include 'posts/includes/paginator.html' %}      
    </article>        
{% endblock %}